apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    app: fly-database
  name: fly-database
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fly-database
    spec:
      # Could also use OnFailure
      restartPolicy: Never
      containers:
      - image: docker.io/rocketlawyer/fly-database
        name: fly-database
        resources: {}
        args:
          - migrate
status: {}
